name: Sync To Gitee

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/tigerdahuacao
          dst: gitee/moss-thirteen
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "git-page"
          force_update: true